#
# Copyright 2018, Nod Labs
#
# standalone unit test for XLA. original code is under:
# tensorflow/tensorflow/compiler/aot/tests/nodcompile_test.cc

SILENT := @
CPP := g++
CPPFLAGS := -g -std=c++11
DEFINES :=

TF_ROOT = /home/subash/deep_learning/tensorflow

VPATH := .

INCLUDES := -I.
INCLUDES += -Ibazel-tensorflow
INCLUDES += -Ibazel-genfiles
INCLUDES += -Ibazel-tensorflow/external/eigen_archive
INCLUDES += -Ibazel-tensorflow/external/boringssl/src/third_party/googletest/include
INCLUDES += -Ibazel-tensorflow/external/protobuf_archive/src
INCLUDES += -Ibazel-tensorflow/external/nsync/public
INCLUDES += -Ibazel-genfiles/tensorflow/compiler/xla

LIB_PATH := -Lbazel-bin/tensorflow/compiler/tf2xla
LIB_PATH += -Lbazel-bin/tensorflow/compiler/aot
LIB_PATH += -Lbazel-bin/tensorflow/compiler/xla/service/cpu
LIB_PATH += -Lbazel-bin/tensorflow/compiler/xla

LIBS := -lxla_compiled_cpu_function
LIBS += -lruntime
LIBS += -lruntime_matmul
LIBS += -lruntime_matvec
LIBS += -lexecutable_run_options
LIBS += -lpthread

SRC := nod_tfcompile_test.cc

BIN := MatMul

OBJS := $(patsubst %.cc,%.o,$(SRC))

%.o: %.cc
	$(SILENT) $(CPP) $(CPPFLAGS) $(INCLUDES) -c $< -o $@

all: clean build

# generated by: bazel build tensorflow/compiler/aot:tfcompile
tf_compile:
	$(TF_ROOT)/bazel-bin/tensorflow/compiler/aot/tfcompile --graph="test_graph_tfmatmul.pb" --config="test_graph_tfmatmul.config.pbtxt" --cpp_class="testgraph::MatMul"

$(BIN): tf_compile out_helper.o out_model.o $(OBJS)
	$(SILENT) $(CPP) $(CPPFLAGS) $(OBJS) out_helper.o out_model.o $(LIB_PATH) $(LIBS) -o $@

build: $(BIN)
.PHONY: build

clean:
	-$(SILENT) rm $(BIN) *.o
.PHONY: clean

# This can be executed only once - broken - python is not being invoked
# from inside the Makefile
gen_graph:
	cd $(TF_ROOT)/tensorflow/compiler/aot/tests
	python3 make_test_graphs.py
	cp test_graph_tfmatmul.pb $(TF_ROOT)
	cp test_graph_tfmatmul.config.pbtxt $(TF_ROOT)
	cd -
.PHONY: gen_graph
